FROM alpine

CMD

ADD






# copy the xxx.tgz to the tmp directory of the container and extract it
ADD xxx.tgz /tmp


# copy the xxx.tgz to the tmp directory of the container and do not extract it
COPY xxx.tgz /tmp
