version: '2'
services:
  databases:
    image: mysql
    networks:
      - xxx-network
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=demo
  web:
    image: nginx
    networks:
      - xxx-network
  os1:
    image: ubuntu
    networks:
      - xxx-network
    tty: true
  os2:
    build: .
    networks:
      - xxx-network
    tty: true
networks:
  xxx-network:
    name: rabbitmq_vnet
    external: true
